# *******************************************************************************
# Copyright (c) 2023 BMW AG
# Copyright (c) 2023 Contributors to the Eclipse Foundation
#
#   See the NOTICE file(s) distributed with this work for additional
#   information regarding copyright ownership.
#
#   This program and the accompanying materials are made available under the
#   terms of the Apache License, Version 2.0 which is available at
#   https://www.apache.org/licenses/LICENSE-2.0.
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#   WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#   License for the specific language governing permissions and limitations
#   under the License.
#
#   SPDX-License-Identifier: Apache-2.0
#   ********************************************************************************

version: '3.8'

services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - db:/var/lib/postgresql/data
      - ./keycloak/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  keycloak:
    build:
      context: .
      dockerfile: Dockerfile
    image: jboss/keycloak:latest
    entrypoint: [ "/bin/sh", "-c" ]
    command:
      - |
        /config/generate-secret.sh &&
        /opt/jboss/tools/docker-entrypoint.sh -b 0.0.0.0
    environment:
      VAULT_TOKEN: ${VAULT_TOKEN}
      VAULT_ADDR: ${VAULT_ADDR}
      SECRET_PATH: ${SECRET_PATH}
      DB_VENDOR: ${DB_VENDOR}
      DB_ADDR: ${DB_ADDR}
      DB_DATABASE: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      KEYCLOAK_IMPORT: /etc/keycloak/realm-export.json -Dkeycloak.profile.feature.upload_scripts=enabled
    ports:
      - "${KEYCLOAK_PORT}:8080"
    depends_on:
      - postgres
    volumes:
      - ./keycloak/realm-export.json:/etc/keycloak/realm-export.json
      - ./keycloak/generate-secret.sh:/config/generate-secret.sh

volumes:
  db:
    driver: local